data<-c(1,2,4,5,6,8,11,15)
data.mean= mean(data)
data.median= median(data)
print(data.mean)
print(data.median)
roots<-sqrt(data)
roots.mean= mean(roots)
roots.median= median(roots)
print(roots.mean)
print(roots.median)
print(roots.mean == sqrt(data.mean))
print(roots.median == sqrt(data.median))
